// <auto-generated />
using System;
using Degen.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Degen.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316215946_InitialMarketData")]
    partial class InitialMarketData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Degen.Domain.MarketData.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Decimals")
                        .HasColumnType("integer")
                        .HasColumnName("decimals");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_symbol");

                    b.ToTable("assets", "market_data");
                });

            modelBuilder.Entity("Degen.Domain.MarketData.Candle", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Interval")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("interval");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("open");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("volume");

                    b.HasKey("InstrumentId", "Interval", "Timestamp")
                        .HasName("pk_candles");

                    b.HasIndex("InstrumentId", "Interval", "Timestamp")
                        .HasDatabaseName("ix_candles_instrument_id_interval_timestamp");

                    b.ToTable("candles", "market_data");
                });

            modelBuilder.Entity("Degen.Domain.MarketData.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaseAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_asset_id");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("exchange");

                    b.Property<string>("ExchangeSymbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("exchange_symbol");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MinOrderSize")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("min_order_size");

                    b.Property<int>("PriceDecimals")
                        .HasColumnType("integer")
                        .HasColumnName("price_decimals");

                    b.Property<int>("QuantityDecimals")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_decimals");

                    b.Property<Guid>("QuoteAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_asset_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("BaseAssetId")
                        .HasDatabaseName("ix_instruments_base_asset_id");

                    b.HasIndex("QuoteAssetId")
                        .HasDatabaseName("ix_instruments_quote_asset_id");

                    b.HasIndex("ExchangeSymbol", "Exchange")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_exchange_symbol_exchange");

                    b.HasIndex("Symbol", "Exchange")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_symbol_exchange");

                    b.ToTable("instruments", "market_data");
                });

            modelBuilder.Entity("Degen.Domain.MarketData.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_watchlists");

                    b.ToTable("watchlists", "market_data");
                });

            modelBuilder.Entity("Degen.Domain.MarketData.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("watchlist_id");

                    b.HasKey("Id")
                        .HasName("pk_watchlist_items");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_watchlist_items_instrument_id");

                    b.HasIndex("WatchlistId")
                        .HasDatabaseName("ix_watchlist_items_watchlist_id");

                    b.ToTable("watchlist_items", "market_data");
                });

            modelBuilder.Entity("Degen.Domain.MarketData.Instrument", b =>
                {
                    b.HasOne("Degen.Domain.MarketData.Asset", "BaseAsset")
                        .WithMany()
                        .HasForeignKey("BaseAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instruments_assets_base_asset_id");

                    b.HasOne("Degen.Domain.MarketData.Asset", "QuoteAsset")
                        .WithMany()
                        .HasForeignKey("QuoteAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instruments_assets_quote_asset_id");

                    b.Navigation("BaseAsset");

                    b.Navigation("QuoteAsset");
                });

            modelBuilder.Entity("Degen.Domain.MarketData.WatchlistItem", b =>
                {
                    b.HasOne("Degen.Domain.MarketData.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchlist_items_instruments_instrument_id");

                    b.HasOne("Degen.Domain.MarketData.Watchlist", null)
                        .WithMany("Items")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchlist_items_watchlists_watchlist_id");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Degen.Domain.MarketData.Watchlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
