name: degen

services:
  api:
    container_name: degen-api
    image: degen-api:latest
    build:
      context: ./apps/api
    ports:
      - "8000:8000"

  web:
    container_name: degen-web
    image: degen-web:latest
    build:
      context: ./apps/web
    ports:
      - "3000:3000"
    depends_on:
      - api
